### ISSUE TITLE
Zooming displays error when window is not focused

### ISSUE THREAD

**Issue by szezjo** [Roller23/Raino#12]
OS: Windows 10 Professional Stolen from University

**What's happening?**
When the window is focused everything works fine. You can even say it works wonderfully fine. Or wonderfully wonderful. It's working nonetheless. But... when you click at some other window (in my example, Calculator, but it's just that Raino window is unfocused, I know, I am Sherlock Holmes) that then using Ctrl+= and Ctrl+- displays this beautiful error. Isn't it beautiful? I think it is.

https://user-images.githubusercontent.com/20361252/113490392-d6eb1500-94c9-11eb-8f0b-54f01a139a5b.mp4

![image](https://user-images.githubusercontent.com/20361252/113490399-e23e4080-94c9-11eb-9fe6-fe047a2e37c3.png)

**Comment by byteingWolf** [comment]
Corrected
